<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Factories\" />
    <None Remove="Builders\" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="Factories\" />
    <Folder Include="Builders\" />
  </ItemGroup>
</Project>
